#!/bin/sh

eth=eth0 
echo "Start PCBA_Function_Test = $eth "

if [ $(ifconfig | grep $eth | wc -l) = 0 ]; then
	ifconfig $eth up 
	sleep 18 
fi

ip=$(ifconfig $eth 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://')
ip=$(ifconfig $eth | awk 'sub(/inet addr:/,""){print $1}')
# echo "ip=$ip"


udhcpc -i $eth & 
#dhclient -r $eth 
sleep 10

if [ "$(ifconfig $eth | awk 'sub(/inet addr:/,""){print $1}' | wc -l)" -eq "0" ]; then
	pid=$(ps ax | grep "udhcpc -i $eth" | grep -v grep | awk '{print $1}')
#	echo "pid=$pid" 
	kill $pid
	echo "ETH $eth   : no link"
	exit 0
fi

if [ "$(ping -I $eth -w 5 8.8.8.8 | grep 8.8.8.8 | wc -l)" -gt "2" ];then
	echo "ETH $eth   : PASS"
else
	echo "ETH $eth   : ...."
fi


